# from S_run_aifeynman import run_aifeynman
# # Make sure your path to the AI-Fetnman directory is correct. 
# # I have used a base directory of /content because that's where a Collab notebook puts the cloned repo
# # Change this to the spot in your machine where you are working from if you need to
# run_aifeynman("/Users/guyharper/development/AI-Feynman/example_data/","example1.txt",30,"14ops.txt", polyfit_deg=3, NN_epochs=400)

import aifeynman

# aifeynman.get_demos("example_data") # Download examples from server
aifeynman.run_aifeynman("./unit_data/", "csv-unit-data.txt", 60, "7ops.txt", polyfit_deg=1, NN_epochs=1, vars_name="Type: Infantry,Type: Cavalry,Type: Chariot,Type: Large Infantry,Type: War Engine,Type: Titan,Type: Large Cavalry,Type: Heavy Infantry,Type: Swarm,Type: Monster,Type: Monstrous Infantry,Base size: 20x20,Base size: 25x25,Base size: 25x50,Base size: 40x40,Base size: 40x40,Base size: 50x50,Base size: 50x50,Base size: 50x100,Base size: 50x50,Base size: 75x75,Base size: 100x40,Base size: 125x50,Base size: 125x50,Base size: 100x100,Base size: 100x80,Base size: 125x100,Base size: 120x40,Base size: 120x40,Base size: 125x100,Base size: 150x50,Base size: 150x100,Base size: 150x50,Base size: 200x80,Base size: 250x100,Base size: 120x80,Base size: 120x80,Base size: 250x100,Base size: 150x100,Base size: 200x100,Base size: 150x100,Base size: 200x120,Base size: 250x150,Base size: 240x80,Base size: 240x80,Base size: 300x100,Base size: 150x200,Base size: 300x100,waver,unwaverable,rout,unitStrength,attacks,d6PlusAttacks,irregular,height,speed,melee,ranged,defence,spells,spellcaster,Big Shield,Cloak of Death,Dread,Duelist,Elite,Elite (Melee),Elite (Ranged),Ensnare,Fly,Frozen,Fury,Headstrong,Ignore Cover,Indirect,Individual,Inspiring,Inspiring (Self only),Iron Resolve,Mighty,Mindthirst,Nimble,Pathfinder,Phalanx,Pot Shot,Radiance of Life,Reload,Scout,Shambling,Shattering,Spellward,Steady Aim,Stealthy,Strider,Very Inspiring,Vicious,Vicious (Melee),Vicious (Ranged),Wild Charge (1),Wild Charge (D3),Blast,Brutal,Crushing Strength,Lifeleech,Piercing,Rallying,Rampage (Melee),Rampage (Ranged),Regeneration,Slayer (Melee),Slayer (Ranged),Thunderous Charge")
